### ISSUE TITLE
Pot files generator creates GETTEXT_PACKAGE.pot

### ISSUE THREAD

**Issue by kobliha** [yast/yast-control-center-gnome#7]
Because of this commit, https://github.com/yast/yast-control-center-gnome/commit/bbd03ac70950dc0597334891da7322c3f040c42e (see my comment there) pot files generator creates GETTEXT_PACKAGE.pot - a textdomain that will not be handled well - in fact, these strings will not be translated.

**Comment by dgdavid** [comment]
This module was marked as obsolete ~2 years ago. Thus, the issue is not longer relevant.
